# tell zsh to parse my custom path for functions
fpath=($ZSH_HOME/functions $fpath)

# load custom completion stuff
autoload -U $ZSH_HOME/functions/*(:t)

# initialize completion system
autoload -U compinit
compinit

# use ls colours for completion
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# use menu completion style when more than <select> matches
# <select> may be fine tuned later on
zstyle ':completion:*' menu select=5

# some useful completion settings
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''

# use smart auto correction
setopt correct

# include the .alias file
test -s $ZSH_HOME/rc/alias && . $ZSH_HOME/rc/alias || true
 
# Use colourful ls and grep
export LS_OPTIONS='--color=auto'
export GREP_OPTIONS='--color=auto'

# Use vi command line mode
bindkey -v

# In vi mode must redo this bind to use history search
bindkey "^R" history-incremental-search-backward

# include prompt configuration
test -s $ZSH_HOME/rc/prompt && . $ZSH_HOME/rc/prompt || true

# Sets title of terminal by printing an escape sequence
function settitle() 
{ 
    printf "\e]0;$@\a" 
}

# Sets the current working directory as the terminal title
function dir_in_title() 
{ 
    settitle $PWD 
}

# Update terminal title to the current working directory 
precmd_functions=(dir_in_title)

# Load private zshrc file
PRIVATE_FILE="$ZSH_HOME/rc/zshrc.private"
test -s $PRIVATE_FILE && . $PRIVATE_FILE || true 
